### ISSUE TITLE
Color palette

### ISSUE THREAD

**Issue by nickmcintyre** [two-ticks/p5.teach.js#26]
@two-ticks I'm trying to use IBM's [color blind safe palette](http://ibm-design-language.eu-de.mybluemix.net/design/language/resources/color-library/) for visualizations in my book whenever possible and find myself copying the hex colors to new sketches a lot. What do you think about exporting the following constants?

```javascript
export const ULTRAMARINE40 = '#648fff';
export const MAGENTA50 = '#dc267f';
export const GOLD20 = '#ffb000';
export const INDIGO50 = '#785ef0';
export const ORANGE40 = '#fe6100';
```

**Comment by JithinKS97** [comment]
I think its a good idea, may be we can include more colours?

**Comment by nickmcintyre** [comment]
Sounds good to me! The IBM color library is a good starting point - here's [another](https://bconnelly.net/posts/creating_colorblind-friendly_figures/).

**Comment by two-ticks** [comment]
Can we have object having the colors instead of exporting separately? 
for example `safeColor.ULTRAMARINE40`
#27 

example: https://editor.p5js.org/radium.scientist/sketches/Kma0_EpQc

**Comment by nickmcintyre** [comment]
Closing this one after merging #27
