### ISSUE TITLE
TypeDocs broken logo

### ISSUE THREAD

**Issue by jeremydouglass** [two-ticks/p5.teach.js#30]
The broken logo "assets/p5-astrik-teach.png" is visible on the docs page:

https://two-ticks.github.io/p5.teach.js/docs/index.html

and the bad link line is here:

https://github.com/two-ticks/p5.teach.js/blob/main/docs/index.html#L64

**Comment by two-ticks** [comment]
Thanks for pointing out! 

https://two-ticks.github.io/p5.teach.js/docs/index.html

```diff
- <img src="assets/p5-astrik-teach.png" alt="astrik-logo" />
+ <img src="https://two-ticks.github.io/p5.teach.js/assets/p5-astrik-teach.png" alt="astrik-logo">
```
 
I want to use relative links but links keep breaking because docs therefore making use absolute links for now, will find a way for relative links soon.
